
export class Cloudinary {
    get client() {
        return this.cloudinary.config({
            cloud_name: 'octdev',
            api_key: '174312832418859',
            api_secret: '5QQT7MQOIxQa4ctxsFU00tRUrIw'
        });
    }
    constructor(private cloudinary: any) {
        this.cloudinary.config({
            cloud_name: 'octdev',
            api_key: '174312832418859',
            api_secret: '5QQT7MQOIxQa4ctxsFU00tRUrIw'
        });
    }

    upload = (path: string,tag:string) => new Promise<any>((resolve, reject) => {
        console.log(path);
        return this.cloudinary.uploader.upload(path, {timeout:600000, resourceType:"auto"}).then(function (image: { url: any; }) {
         
            console.log("** File Upload (Promise)");
            console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
            console.log("* " + image.url);
            resolve(image.url)
        })
        .catch(function (err: any) {
            console.log("** File Upload (Promise)");
            if (err) { console.warn(err); }
            reject(err)
        });;
    })

    test = (path: string) => {
        this.cloudinary.uploader.upload("uploads/beef.jpg", { tags: 'basic_sample' })
            .then(function (image: { public_id: string; url: string; }) {
                console.log();
                console.log("** File Upload (Promise)");
                console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
                console.log("* " + image.public_id);
                console.log("* " + image.url);
            })
            .catch(function (err: any) {
                console.log();
                console.log("** File Upload (Promise)");
                if (err) { console.warn(err); }
            });
        // this.cloudinary.uploader.upload('http://res.cloudinary.com/demo/image/upload/couple.jpg', { tags: "basic_sample" }, function (err, image) {
        //     console.log();
        //     console.log("** Remote Url");
        //     if (err) { console.warn(err); }
        //     console.log("* " + image.public_id);
        //     console.log("* " + image.url);
        //   });
    }
}