export const newSessionRoutes = [
  { path: '/api/auth/login', method: 'POST' },
  { path: '/api/auth/register', method: 'POST' },
  { path: '/api/auth/token', method: 'POST' },
  { path: '/api/repayment/plan', method: 'POST' },
  { path: '/api/account/enquiry', method: 'POST' },
  { path: '/api/common/validatebvn', method: 'POST' },
  { path: '/api/auth/verify', method: 'POST' },
  { path: '/api/auth/resetpassword', method: 'POST' }
];
export const authRoutes = [
  { path: "/api/auth/refresh-session", method: "GET" },
  { path: '/api/earnings/apply', method: 'POST' }, 
  { path: '/api/earnings/getLatestEarnings', method: 'GET' },
  { path: '/api/earnings/search', method: 'POST' },
  { path: '/api/earnings', method: 'GET' },
  { path: '/api/earnings/searchToProcess', method: 'POST' },
  { path: '/api/earnings/updateStatus', method: 'POST' },
  { path: '/api/earnings/getEarningDetails', method: 'GET' },
  { path: '/api/earnings/getEarningLogDetails', method: 'GET' },
  { path: '/api/earnings/getAllEarningDetails', method: 'GET' },
  { path: '/api/earnings/getAllEarningLogDetails', method: 'GET' },
  { path: '/api/earnings/getApprovedEarning', method: 'GET' },
  { path: '/api/earnings/notifyTopUp', method: 'GET' },
  { path: '/api/earnings/getTopUps', method: 'GET' },
  { path: '/api/earnings/topUp', method: 'PATCH' },
  { path: '/api/earnings/notifyLiquidation', method: 'GET' },
  { path: '/api/earnings/getLiquidations', method: 'GET' },
  { path: '/api/earnings/liquidate', method: 'PATCH' },
  { path: '/api/earningspayout', method: 'GET' },
  { path: '/api/earningspayout/getPayoutHealth', method: 'GET' },
  { path: '/api/earningspayout/pay', method: 'POST' },
  { path: '/api/auth/password', method: 'PUT' },
  { path: '/api/notification/send', method: 'POST' },
  { path: '/api/notification/sendtomultiple', method: 'POST' },
  { path: '/api/notification/subscribe', method: 'POST' },
  { path: '/api/notification/notifyCustomer', method: 'POST' },
  { path: '/api/users/create', method: 'POST' },
  { path: '/api/auth/logout', method: 'GET' },
  { path: '/api/auth/passwordChange', method: 'PUT' },
  { path: '/api/users', method: 'GET' },
  { path: '/api/earnings', method: 'GET' },
  { path: '/api/account', method: 'GET' },
  { path: '/api/account/updateAccounts', method: "POST" },
  { path: '/api/loans/getLatestLoan', method: 'GET' },
  { path: '/api/loans/search', method: 'POST' },
  { path: '/api/loans/create', method: 'POST' },
  { path: '/api/loans', method: 'GET' },
  { path: '/api/loans/searchToProcess', method: 'POST' },
  { path: '/api/loans/updateStatus', method: 'POST' },
  { path: '/api/loans/getLoanDetails', method: 'GET' },
  { path: '/api/loans/getLoanLogDetails', method: 'GET' },
  { path: '/api/loans/getDisbursedLoan', method: 'GET' },
  { path: '/api/repayment/getRepayments', method: 'GET' },
  { path: '/api/repayment/getRepaymentHealth', method: 'GET' },
  { path: '/api/repayment/repay', method: 'POST' },
  { path: '/api/customer', method: 'GET' },
  { path: '/api/customer/all', method: 'GET' },
  { path: '/api/customer/bvn', method: 'GET' },
  { path: "/api/customer/getById", method: "GET" },
  { path: '/api/customer/employers', method: 'GET' },
  { path: '/api/customer/earningEmployment', method: 'GET' },
  { path: '/api/customer/companies', method: 'GET' },
  { path: '/api/customer/nok', method: 'GET' },
  { path: '/api/customer/updateCustomerBVN', method: 'PUT' },
  { path: '/api/customer/collaterals', method: 'GET' },
  { path: '/api/customer/update', method: 'PUT' },
  { path: '/api/customer/updateNOK', method: 'PUT' },
  { path: '/api/customer/shareholders', method: 'POST' },
  { path: '/api/document/upload', method: 'POST' },
  { path: '/api/document/download', method: 'POST' },
  { path: '/api/document/getAll', method: 'GET' },
  { path: '/api/document/attachLoan', method: 'GET' },
  { path: '/api/files/merge_chunks', method: 'POST' }
];



export const ApiControllers = [...newSessionRoutes,...authRoutes].map(route=>{

  return route.path.split("/")[2];
})